### ISSUE TITLE
Problem with zip, which is not a result

### ISSUE THREAD

**Issue by julianu** [proteomexchange/px-submission-tool#1]
When I want to use a ZIP archive as source for other, it breaks the px-tool (Linux, px-submission-tool 2.2.3).
The file gets automatically annotated as result. If I change it into other and click next, nothing happens, no even an error in the console, just flashing up the progress bar and closing it again. (Funnily, also leaving it as result has the same result).
Changing the file into a tgz lets it pass into the next step.

**Comment by ruiwanguk** [comment]
Hi Julian, 

Thank you very much for reporting the bug. We are working on addressing the issue now. 

Will get back to you once this is fixed. 

Regards,
Rui

**Comment by ruiwanguk** [comment]
Hi Julian,

For us to replicated the problem, would it be possible to provide us with an example? 

Much appreciated. 

Regards,
Rui

**Comment by julianu** [comment]
Hej Rui,

 

Sure.

The ZIP did not work, the tgz (same file, but tar-gzipped) did.

I only tried on my linux machine using OpenJDK.

 

Regards,

Julian

 

Von: Rui Wang [mailto:notifications@github.com] 
Gesendet: 30 January 2015 11:15
An: proteomexchange/px-submission-tool
Cc: Julian Uszkoreit
Betreff: Re: [px-submission-tool] Problem with zip, which is not a result (#1)

 

Hi Julian,

For us to replicated the problem, would it be possible to provide us with an example? 

Much appreciated. 

Regards,
Rui

**Comment by ruiwanguk** [comment]
Thx, did you attached the file?

If this file part of your recent submission, just let us know the name, we can find it on our end.

**Comment by julianu** [comment]
works for me now, i think you can close the issue

**Comment by ruiwanguk** [comment]
Thanks a lot for the feedbacks.
