### ISSUE TITLE
Increase sample related information

### ISSUE THREAD

**Issue by javizca** [proteomexchange/px-submission-tool#10]
There are several things that can be done to increase sample related information in the short-medium term:
- For complete submissions: make mandatory the experimental factor.
- In both types of submissions, but especially partial, provide human readable names of raw files.

In addition:
- Extra optional file. Label: experimental factor file -> Same format than MaxQuant.

**Comment by Tobias-Ternent** [comment]
A typical experimental design template MaxQuant file has content like:

```
Name	Fraction	Experiment
121026OTc2_TDM-AU-0324-NKI-42_010	1	OR-36
121004OTc2_TDM-AU-0324-N-1_008	1	OR-29
121004OTc2_TDM-AU-0324-N-2_017	1	OR-04
```

**Comment by ypriverol** [comment]
This will be considered in future use cases in the annotation system please follow this issue:https://github.com/PRIDE-Archive/pride-archive-pipelines/issues/6
