### ISSUE TITLE
Include mandatory database for proteogenomics studies

### ISSUE THREAD

**Issue by javizca** [proteomexchange/px-submission-tool#11]
I don't know if the workflow "proteogenomics" exists, but it that's not the case, create it.

For those types of datasets, make mandatory the submission of database files (for both complete and partial submissions).

**Comment by ypriverol** [comment]
@javizca @Tobias-Ternent in my opinion all complete submission should submit they data as mandatory or at least we should recommend this, in terms of reproducibility, review, etc. 

It is practically impossible to review a dataset or reproduce the original results if the database is not provided. This is in any case for most of the cases a fasta file with less than 1G of size. If we "recommend" the submission of this fasta files we don't need to make differences between a complete submission and a proteogenomics submission. It is also something that the community is asking.
