### ISSUE TITLE
Prevent result files to be included in a 'partial' submission

### ISSUE THREAD

**Issue by Tobias-Ternent** [proteomexchange/px-submission-tool#22]
Currently it is possible to include 'result' files in a 'partial' submission. This is not allowed and should be prevented.

**Comment by edeutsch** [comment]
I am startled by this. Why would we want to disallow result files ever?
Surely result files should be required for a partial submission. It is sad
that they cannot be fully read by the repository, but one may presume that
some interested party might be able to read and use them. And perhaps
someday the repository might be able to go back and read them. And surely
they should be archived in any case. Am I misunderstanding?





*From:* Tobias Ternent [mailto:notifications@github.com]
*Sent:* Thursday, October 29, 2015 7:23 AM
*To:* proteomexchange/px-submission-tool <
px-submission-tool@noreply.github.com>
*Subject:* [px-submission-tool] Prevent result files to be included in
'partial' a submission (#22)



Currently it is possible to include 'result' files in a 'partial'
submission. This is not allowed and should be prevented.

—
Reply to this email directly or view it on GitHub
<https://github.com/proteomexchange/px-submission-tool/issues/22>.[image:
Image removed by sender.]

**Comment by Tobias-Ternent** [comment]
Hi Eric,

I think may have misunderstood what I had meant. We classify PRIDE XML or mzIdentML as 'result' files with the px submission tool. These are supposed to be for 'complete' submissions only. So the tool should prevent a user from adding 'result' files to a 'partial' submission.

'Partial' submissions still have to have identification files  included as 'search' data along with the 'raw' data. Sorry for any confusion about this.

In the future, if 'result' files can be generated for a particular 'partial' project, then it can be updated to be 'complete' through a 'resubmission' as long as the project is still private. If such a project was public, then perhaps a new submission for reanalysis data would be best.

**Comment by edeutsch** [comment]
Ah, I think I see. If there is a ‘result’ file present, then it should be
classified as complete by definition, not partial. I conflated ‘result’
files and ‘search’ files.



Thanks,

Eric





*From:* Tobias Ternent [mailto:notifications@github.com]
*Sent:* Thursday, October 29, 2015 7:51 AM
*To:* proteomexchange/px-submission-tool
*Cc:* Eric Deutsch
*Subject:* Re: [px-submission-tool] Prevent result files to be included in
a 'partial' submission (#22)



Hi Eric,

I think may have misunderstood what I had meant. We classify PRIDE XML or
mzIdentML as 'result' files with the px submission tool. These are supposed
to be for 'complete' submissions only. So the tool should prevent a user
from adding 'result' files to a 'partial' submission.

'Partial' submissions still have to have identification files included as
'search' data along with the 'raw' data. Sorry for any confusion about this.

In the future, if 'result' files can be generated for a particular
'partial' project, then it can be updated to be 'complete' through a
'resubmission' as long as the project is still private. If such a project
was public, then perhaps a new submission for reanalysis data would be best.

—
Reply to this email directly or view it on GitHub
<https://github.com/proteomexchange/px-submission-tool/issues/22#issuecomment-152203658>
.

**Comment by mbdebian** [comment]
This is already implemented according to what I've seen in the code [here](https://github.com/proteomexchange/px-submission-tool/blob/c9dfe091a8f9f6f5f8b5ab1d97307590688c9cb4/src/main/java/uk/ac/ebi/pride/gui/task/FileScanAndValidationTask.java#L160), please, see screen capture as well.
<img width="800" alt="captura de pantalla 2016-08-04 a las 14 41 27" src="https://cloud.githubusercontent.com/assets/8855107/17404029/3bba822a-5a52-11e6-98d4-9b176688ff7d.png">
