### ISSUE TITLE
Submission_Summary_File_Format.pdf contains mistakes in CV Paramd, BRENDA instead of BTO

### ISSUE THREAD

**Issue by Tobias-Ternent** [proteomexchange/px-submission-tool#26]
In the Submission_Summary_File_Format.pdf document included in the Help directory, the tissue CV Params are defined wrongly like this:
[BRENDA, BTO:0000142, brain,]
instead of:
[BTO, BTO:0000142, brain,]
There are 5 total occurrences of this in the PDF that should be updated.

**Comment by mbdebian** [comment]
This is now fixed on branch [helpDocumentationBugFix](https://github.com/proteomexchange/px-submission-tool/tree/helpDocumentationBugFix), ready to merge with master branch.
The help document has been updated and reformatted to make it easier to read by the user.
