### ISSUE TITLE
Support non-PRIDE PX repositories

### ISSUE THREAD

**Issue by Tobias-Ternent** [proteomexchange/px-submission-tool#29]
The PX Submission tool only supports submitting data to the PRIDE repository. With more partners joining the PX consortium, it might be best if the tool can be updated to support other repositories as well.

This will likely mean a lot of changes are needed, which can be detailed and estimated in the future,

**Comment by mbdebian** [comment]
@Tobias-Ternent , would you say we can close this one?

**Comment by mbdebian** [comment]
@Tobias-Ternent , I'm not sure if this one still makes sense as future work, please, let me know if it doesn't, so I can close this issue.
Thanks

**Comment by javizca** [comment]
This is no longer something we can afford to do, at least for some years to come.

**Comment by ypriverol** [comment]
This issue can be close

**Comment by mbdebian** [comment]
Ok @javizca , then it makes sense to close the issue.
