### ISSUE TITLE
Tool does not build?

### ISSUE THREAD

**Issue by mvaudel** [proteomexchange/px-submission-tool#30]
Hi,

I made a fresh checkout of the code and it does not seem to build?

I get the following error:

```
Could not resolve dependencies for project uk.ac.ebi.pride.px:px-submission-tool:jar:2.3.0: Could not find artifact com.asperasoft:aspera-faspmanager:jar:2.7.0.42750 in nexus-ebi-repo (http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/)
```

Thanks for your help,

Marc

**Comment by Tobias-Ternent** [comment]
Hi Marc,

Please can you see the comment from @ypriverol for the instructions about how to manually install this library? It's for the same issue, but with the PRIDE Inspector tool.

https://github.com/PRIDE-Toolsuite/pride-inspector/issues/54#issuecomment-160621241

**Comment by mvaudel** [comment]
Great, thanks!
