### ISSUE TITLE
Allow multiple selection of raw files

### ISSUE THREAD

**Issue by mvaudel** [proteomexchange/px-submission-tool#31]
Hi guys,

We have just submitted some data, 3 sets of 150 raw files. Did I miss how to do multiple selection in the table when linking raw files to an id file? It is really a pain to select 3 times 150 files one by one...

When clicking on add, the tool hangs, would be nice to have a progress bar :)

Best regards,

Marc

**Comment by Tobias-Ternent** [comment]
Hi Marc,

You're right, there's no way to select multiple files when you want to map the relationships (e.g. relate 1 'result' file to say 10 'raw' files). Ticking each file is the only way forward.

The tool does try to automatically add the file relationships based off the filename, e.g. Run_A.mzid will be mapped to Run_A.raw by itself. This is not always perfect, and indeed if the filenames are very different then there will be no automatic mapping at all.

I agree, it would be good to be able to select multiple files and then click one button to add them all in one go. Indeed it would save you from the potential monotony of hundreds and hundreds of clicks.

This is not much of a problem with a small number of files, but gets worse the more files you have. If you're interested, it's possible to make a script to create, or manually edit an existing, summary 'submission.px' file:
http://www.ebi.ac.uk/pride/help/archive/faq#export-summary-without-PX-tool
This pre-prepared submission.px file then can be loaded into the tool as a 'bulk' submission. This is more useful for labs producing data with thousands of files, and wanting to make many submissions.
Section 6, page 36: 
http://www.proteomexchange.org/sites/proteomexchange.org/files/documents/px_submission_tutorial2.pdf

**Comment by ypriverol** [comment]
@sureshhewabi Can you check if this can be implemented before the release.

**Comment by sureshhewabi** [comment]
Done implemented in version 2.4.8
