### ISSUE TITLE
There is no Readme or Wiki section

### ISSUE THREAD

**Issue by Tobias-Ternent** [proteomexchange/px-submission-tool#32]
The Readme and Wiki sections should be filled out with good information.

**Comment by ypriverol** [comment]
Improve the README. @mbdebian I think this would be important to (at least) add a couple of useful links here about how to use the information, where to find the information, etc.

**Comment by mbdebian** [comment]
What would you guys like to see in the read me?
What about general information on how to download, unpack the tool, launch it and a link to a user manual where they can learn how to make submissions?

**Comment by Tobias-Ternent** [comment]
Yes, I think general info as you've mention would be for the best, about downloading, extracting, launching the tool and to the manual document. Also can link to the PRIDE submission help web page: http://www.ebi.ac.uk/pride/help/archive/submission
Also we have a Troubleshooting section on the PRIDE FAQ for help when the PX Submission Tool won't launch, or when Aspera won't connect properly:
http://www.ebi.ac.uk/pride/help/archive/faq#Troubleshooting
Perhaps you can link to that or copy/paste the information that's useful?

For the Wiki I think it would be best to also explain what the PX consortium is, what PRIDE is, why the tool is needed, etc.

**Comment by ypriverol** [comment]
This will be a move to the Pride Web documentation
