### ISSUE TITLE
Able to make simultaneous submissions from multiple instances

### ISSUE THREAD

**Issue by Tobias-Ternent** [proteomexchange/px-submission-tool#34]
It's possible to launch multiple instances of the PX Submission Tool at the same time. And so it's possible to simultaneously make more than 1 submission concurrently. This causes problem with uploading data - files for multiple submissions end up in the same target directory, submission.px files are overwritten because they use the same name, and it's left in a bad state that needs to be cleaned up manually. Multiple internal tickets are created, that all point to the same target submission directory. 

It would be best to avoid this completely, by limiting to only 1 instance of the submission tool being run.

**Comment by ypriverol** [comment]
@mbdebian this is something you can implement eaily in Java and can be a nice feature to add. I have a code already in the inspector to check this. I can share it with you. 

https://github.com/PRIDE-Toolsuite/pride-inspector/blob/master/src/main/java/uk/ac/ebi/pride/toolsuite/gui/PrideInspector.java#L72

**Comment by Tobias-Ternent** [comment]
Fixed as of v2.3.3.
