### ISSUE TITLE
Submission process feedback from user

### ISSUE THREAD

**Issue by mbdebian** [proteomexchange/px-submission-tool#35]
Hi guys, I'm working on a little extension for this tool where, at the end of the submission process, it gives the user a chance to provide some feedback.

Please, have a look at the attached screen capture where the upload progress bar has been moved to the top of the submission screen (once the process is finished), and a new are with 5 smiley faces that will be clickable buttons will allow the user to select the level of satisfaction regarding the submission process, and there is an optional box bellow those faces to provide more detailed feedback.

Feedback will be collected once the user clicks on "New", "Finish" or if the user closes the application.

I think this is the right place for collecting this kind of data, just when the submission has been completed. The default selection will cover the majority of cases where the user is not excited enough to pat you on the back, and not angry enough bomb your inbox.

Please, don't pay much attention to how it looks, but to whether this makes sense or not from the UX/UI point of view.

Cheers,
Manuel

![captura de pantalla 2016-04-27 a las 8 51 51](https://cloud.githubusercontent.com/assets/8855107/14845532/adde2f22-0c56-11e6-93be-7a5bf9c42452.png)

**Comment by mbdebian** [comment]
Do you guys like this approach or it would be better to change that "Finish" button for a "Feedback" button, so the feedback form is displayed on a separate panel?

**Comment by javizca** [comment]
I think "Finish" is fine. If they have not explicitly provided any feedback, they will be prompted with a window to do it before the application is closed.

**Comment by mbdebian** [comment]
I just finished designing a better look&feel for the rating icons, and coding a better interactive behavior.

Now I'll work on the back-end for submitting the feedback data somewhere.

Let me know what you think

https://youtu.be/NAf-uLVxF9o

**Comment by javizca** [comment]
ok, perfect. It looks perfectly fine for me.

**Comment by mbdebian** [comment]
Attached you can see feedback buttons when they are unselected, mouse rollover, and selected.

Now they're more explicit for the user.

Let me know what you think.


![captura de pantalla 2016-05-12 a las 10 22 21](https://cloud.githubusercontent.com/assets/8855107/15209918/b31b5b82-182b-11e6-8183-10de1d46997e.png)
![captura de pantalla 2016-05-12 a las 10 22 29](https://cloud.githubusercontent.com/assets/8855107/15209921/b7fdbe7e-182b-11e6-9ba0-7fc3857d8c00.png)
![captura de pantalla 2016-05-12 a las 10 22 32](https://cloud.githubusercontent.com/assets/8855107/15209925/ba018e1c-182b-11e6-9689-3e2f20649a86.png)
![captura de pantalla 2016-05-12 a las 10 22 34](https://cloud.githubusercontent.com/assets/8855107/15209938/c5b8eeee-182b-11e6-9a78-0e039a69166a.png)
![captura de pantalla 2016-05-12 a las 10 22 37](https://cloud.githubusercontent.com/assets/8855107/15209941/c7616be0-182b-11e6-87a4-94e2754f5bdb.png)
![captura de pantalla 2016-05-12 a las 10 22 39](https://cloud.githubusercontent.com/assets/8855107/15209943/c91bdfc4-182b-11e6-9914-fea88337e9e4.png)
![captura de pantalla 2016-05-12 a las 10 22 41](https://cloud.githubusercontent.com/assets/8855107/15209944/cacc905c-182b-11e6-9188-6972896d6b9b.png)

**Comment by ypriverol** [comment]
+1

**Comment by mbdebian** [comment]
This is now implemented on 2.3.2-SNAPSHOT, distributed for testing within the team
