### ISSUE TITLE
Update descriptions for public/private projects using the submission tool

### ISSUE THREAD

**Issue by Tobias-Ternent** [proteomexchange/px-submission-tool#36]
Currently there is no way for a user to directly change the metadata for a submitted project, e.g. the title, project description. The only way to do this is to email into pride-support and request these changes, which have to be performed by someone in PRIDE manually.

It would be nice if we could provide this directly to users. Potentially this could be done with a new screen/option on the PX Submission Tool?

**Comment by ypriverol** [comment]
This will be implemented on the new PRIDE using the web interface.
