### ISSUE TITLE
Manual file associations are lost upon using Bulk mode

### ISSUE THREAD

**Issue by vdtoorn** [proteomexchange/px-submission-tool#37]
I found that a user, after having associated many search files to raw files and saving to a submission.px file, had incorrect file associations. Reviewing the code, I found it's because the automatic association processing was run even if the submission.px file was loaded with the "bulk mode" button. Following the code logic, this would not only maintain the associations that were in the px file but also add the associations from the automatic association code (which were wrong in this case). Then, manual correction was necessary again.
To circumvent this problem, I've created the attached patch. When loading in the px file, a flag is set in the AppContext, indicating bulk mode. In the code that checks the files and associations, I disable the automatic association if the bulk mode is set, so the file associations are not changed from the px file.
[px-submission-tool-file-mapping-patch.zip](https://github.com/proteomexchange/px-submission-tool/files/323602/px-submission-tool-file-mapping-patch.zip)

**Comment by ypriverol** [comment]
Hi @vdtoorn thanks for reporting the issue and fixing it. We can integrate this code and patch in our code. Can you fork the code, make a pull request? Would be easy to do it in that way and integrate it with our current branch development.

**Comment by vdtoorn** [comment]
Hi Yasset, I've created the request!
Henk

**Comment by ypriverol** [comment]
@vdtoorn thanks for your contribution and feel free to report and contribute with other features in PX. We are actively developing PX. PR accepted already https://github.com/proteomexchange/px-submission-tool/pull/38#event-698721639
+1
