### ISSUE TITLE
Training mode

### ISSUE THREAD

**Issue by mbdebian** [proteomexchange/px-submission-tool#39]
Hi guys (  @ypriverol @Tobias-Ternent @attilacsordas ),

Compiling each version of the tool just to distribute it for training purposes is not very pretty. So, while working on mzTab support, I just put together a new feature in the px-submission-tool called "Training mode", which, when active, it will not do any submission and will allow the user to get away with no feedback provision.

I got the core functionality working and tested, and it is shown to the user as a check box on the Welcome screen.

Extra visual aids for the user regarding this feature can be easily implemented, but I want to run this through you before going further.

Please, see attached screen capture.

Cheers,
Manuel

![captura de pantalla 2016-08-01 a las 14 10 26](https://cloud.githubusercontent.com/assets/8855107/17294954/b6cde7ee-57f1-11e6-9663-78ddf6173d7d.png)

**Comment by mbdebian** [comment]
I just added a very visual flag to let the user know when the application is working in training mode or not.

Please, see attached screen capture.

![captura de pantalla 2016-08-01 a las 16 58 04](https://cloud.githubusercontent.com/assets/8855107/17300209/533b5992-5809-11e6-84cd-ea8872219b0e.png)

**Comment by javizca** [comment]
For me this is perfectly fine. Thanks! Two things to consider:
- Training mode: I would put (not actual submission at the end). Maybe also autofill the username and password for the users.
- The training tutorial needs to be updated to take this into account.

**Comment by mbdebian** [comment]
After some discussion, the "training mode" is implemented in the tool, and can be activated by editing config/config.props option 'training.mode.status = on'
In that same file there is a short description of this operational mode.
The feedback submission part has been extended to be aware of this, so no feedback is submitted/required when working in 'training mode'.
On the interface side, we agreed on hiding the training mode activation checkbox unless it is active, in which case it will show up to give the user the chance of quickly deactivate it for the current session, as a way to avoid closing the application, editing the config file, and relaunching the software.
We probably need to address the "training tutorial".
