### ISSUE TITLE
Requested interface changes

### ISSUE THREAD

**Issue by mbdebian** [proteomexchange/px-submission-tool#44]
Hi guys, I'm going to use this issue as a place for discussing about some changes that have been requested on the interface of the tool.

**Comment by mbdebian** [comment]
This is how the main screen looks like, right now.
![screen shot 2017-03-06 at 12 49 46](https://cloud.githubusercontent.com/assets/8855107/23610708/70679f50-026b-11e7-9447-8129a3202dbb.png)

**Comment by mbdebian** [comment]
These are the underlying text messages I've changed in the application (one change per comment, so we can have a thread per change)

(original) result.file.type.note = <html><b>RESULT</b> (required): Experimental results, either PRIDE XML or mzIdentML files are supported</html>
(new) result.file.type.note = <html><b>RESULT</b> (required): Please, provide Experimental Results in any of the supported formats, as explained in the accompanying documentation.</html>

**Comment by mbdebian** [comment]
(original) peak.file.type.note = <html><b>PEAK</b> (required for mzIdentML/ optional for PRIDE XML): peak list files such as mgf, dta, ms2 or pkl, or processed mzML, mzXML files</html>

(new) peak.file.type.note = <html><b>PEAK</b> Peak list files such as mgf, dta, ms2 or pkl, or processed mzML, mzXML files, as per of the requirements described in the documentation for the data format chosen for submitting Experiment Results</html>

**Comment by mbdebian** [comment]
(original) welcome.full.submission.content = <html><p>Use this option if you can provide your identification results in either mzIdentML or PRIDE XML format. It will then be possible to fully integrate the results in PRIDE and visualise them (e.g. as required by MCP).</p> <br/> <p>In addition to a PXD identifier, a permanent Digital Object Identifier (DOI) will be provided to uniquely identify the dataset.</p></html>

(new) welcome.full.submission.content = <html><p>Use this option if you can provide your identification results in any of the supported formats (see accompanying documentation for more details). It will then be possible to fully integrate the results in PRIDE and visualise them (e.g. as required by MCP).</p> <br/> <p>In addition to a PXD identifier, a permanent Digital Object Identifier (DOI) will be provided to uniquely identify the dataset.</p></html>

**Comment by mbdebian** [comment]
(original) welcome.partial.submission.content = <html><p>You should only choose this option if your search results cannot be converted to mzIdentML or PRIDE XML. Identifications will not be integrated in PRIDE. However, files will be made available to download (and maybe visualised with other external tools).</p> <br/> <p> A PXD identifier will be provided to uniquely identify the dataset, but not a DOI.</p></html>

(new) welcome.partial.submission.content = <html><p>You should only choose this option if your search results cannot be converted to of the supported formats (see accompanying documentation for more details). Identifications will not be integrated in PRIDE. However, files will be made available to download (and maybe visualised with other external tools).</p> <br/> <p> A PXD identifier will be provided to uniquely identify the dataset, but not a DOI.</p></html>

**Comment by mbdebian** [comment]
(original) prerequisite.result.file.desc = PRIDE XML or mzIdentML(+ spectra)

(new) prerequisite.result.file.desc = Supported formats specified in the accompanying documentation (+ spectra)

**Comment by javizca** [comment]
Could you please make a build for me? (I guess it is not too much work). It is much easier to spot things in the actual GUI

**Comment by mbdebian** [comment]
Changes on the interface are now completed.
