### ISSUE TITLE
OLS timeout proxy server issue

### ISSUE THREAD

**Issue by wtsi-proteomics** [proteomexchange/px-submission-tool#46]
Using version 2.4.3 with proxy set in config.props (settings which work with previous releases), am able to connect and submit project however, if I use the OLS dialogue to add any none default terms the dialogue is unable to connect to the OLS service and timesout. Have tested on none proxied connection and works fine so possibly something to do with OLS not using proxy settings to connect to service?

**Comment by ypriverol** [comment]
This issue have been solve.
