### ISSUE TITLE
MzML and MzXML will be considred as Peak List, RAW mandatory 

### ISSUE THREAD

**Issue by ypriverol** [proteomexchange/px-submission-tool#58]
Related with a change in the specification of PRIDE submission https://github.com/PRIDE-Archive/pride-archive-pipelines/issues/8

**Comment by sureshhewabi** [comment]
This seems already implemented in the current version
![screen shot 2019-01-07 at 13 40 16](https://user-images.githubusercontent.com/5387193/50771191-ccf1f180-1281-11e9-9088-18cfeb7a11b4.png)
