### ISSUE TITLE
Do not allow mzIdentML files which reference raw files

### ISSUE THREAD

**Issue by Tobias-Ternent** [proteomexchange/px-submission-tool#6]
We do not support mzIdentML files which referencing raw files
http://www.ebi.ac.uk/pride/help/archive/faq#mzid-with-rawfiles-only
This should be checked for and prevented at the time of making a 'complete' submission.

**Comment by Tobias-Ternent** [comment]
Fixed with https://github.com/proteomexchange/px-submission-tool/commit/3040519208e1c4ea0e6fdc30917698ab62f2b353 ready for next release.

**Comment by ypriverol** [comment]
Can you check that this is supported now @sureshhewabi

**Comment by sureshhewabi** [comment]
Checked in px-submission-tool-2.4.8-SNAPSHOT
This has been already fixed
<img width="1023" alt="screen shot 2018-08-29 at 10 36 56" src="https://user-images.githubusercontent.com/5387193/44779532-a4414900-ab77-11e8-8b61-d8f2a9b87f10.png">
