### ISSUE TITLE
Enable Term ID Search

### ISSUE THREAD

**Issue by sureshhewabi** [proteomexchange/px-submission-tool#67]
To be able to search a parameter through the OLS, only the "Term Name Search" tab is active. Why are others tabs inactive and especially the "Term ID Search" (cf. attached print screen)? For example, knowing the NCBI TaxonID is useless without this tab and for being able to select the "Trypanosoma" species, I was happy to obtain it with this rule "^Trypanosoma$".

Reference:
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=333159

**Comment by selvaebi** [comment]
done in https://github.com/proteomexchange/px-submission-tool/pull/79
