### ISSUE TITLE
Add CV param for No PTM in submission tool

### ISSUE THREAD

**Issue by sureshhewabi** [proteomexchange/px-submission-tool#76]
`java.lang.IllegalArgumentException: Modification annotation is mandatory submissions!`

Suggested from Gerhard:
The PX submission tool seems not checking if there is modification specified,
which leads later to problems in runPublications, see e.g.
more ./log/publication/PXD014872-publication.log
more ./log/publication/PXD016394-publication.log
so that a resubmission is required.
Can one make sure by the PX submission tool, that
[PRIDE, PRIDE:0000398, No PTMs are included in the dataset, ]
is included, when the user doesn't specify a modification?

**Comment by selvaebi** [comment]
done in https://github.com/proteomexchange/px-submission-tool/pull/77
